CREATE TABLE runtime_state (
    id TINYINT PRIMARY KEY CHECK (id = 1),
    database_id BIGINT NOT NULL,
    incarnation BIGINT NOT NULL,
    resetlogs_id BIGINT NOT NULL,
    durable_scn NUMERIC(20, 0) NOT NULL,
    durable_thread INTEGER NOT NULL,
    durable_sequence BIGINT NOT NULL,
    durable_offset NUMERIC(20, 0) NOT NULL,
    low_watermark_scn NUMERIC(20, 0),
    low_watermark_thread INTEGER,
    low_watermark_sequence BIGINT,
    low_watermark_offset NUMERIC(20, 0),
    jsonl_file_number BIGINT NOT NULL,
    jsonl_fsync_offset BIGINT NOT NULL,
    config_fingerprint CHAR(64) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE table_schema_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    container_name VARCHAR(128) NOT NULL,
    owner_name VARCHAR(128) NOT NULL,
    table_name VARCHAR(128) NOT NULL,
    object_id BIGINT NOT NULL,
    data_object_id BIGINT NOT NULL,
    effective_scn NUMERIC(20, 0) NOT NULL,
    schema_json CLOB NOT NULL,
    ddl_type VARCHAR(64) NOT NULL,
    ddl_text CLOB NOT NULL,
    source VARCHAR(16) NOT NULL CHECK (source IN ('initial', 'flashback', 'redo')),
    drop_tombstone BOOLEAN NOT NULL,
    CONSTRAINT uq_table_schema_version UNIQUE (
        container_name, owner_name, table_name, effective_scn
    )
);

CREATE INDEX idx_table_schema_lookup ON table_schema_history (
    container_name, owner_name, table_name, effective_scn DESC
);
