/*
 * Manual RedoReplicator source and privilege validation.
 *
 * Copyright (C) 2026 RedoReplicator contributors
 *
 * This file is part of RedoReplicator and is licensed under
 * the GNU Affero General Public License version 3 or later.
 */

WHENEVER SQLERROR EXIT SQL.SQLCODE

SELECT VERSION_FULL FROM SYS.V_$INSTANCE;

SELECT DBID,
       CURRENT_SCN,
       LOG_MODE,
       FORCE_LOGGING,
       SUPPLEMENTAL_LOG_DATA_MIN,
       CDB
  FROM SYS.V_$DATABASE;

SELECT INCARNATION#, RESETLOGS_ID
  FROM SYS.V_$DATABASE_INCARNATION
 WHERE STATUS = 'CURRENT';

SELECT SYS_CONTEXT('USERENV', 'DB_NAME') AS DATABASE_NAME,
       SYS_CONTEXT('USERENV', 'CON_NAME') AS CONTAINER_NAME
  FROM DUAL;

SELECT COUNT(*) FROM SYS.USER$;
SELECT COUNT(*) FROM SYS.OBJ$;
SELECT COUNT(*) FROM SYS.TAB$;
SELECT COUNT(*) FROM SYS.COL$;
SELECT COUNT(*) FROM SYS.CDEF$;
SELECT COUNT(*) FROM SYS.CCOL$;
SELECT COUNT(*) FROM SYS.ECOL$;
SELECT COUNT(*) FROM SYS.LOB$;
SELECT COUNT(*) FROM SYS.TS$;
